name: Deploy Next.js (web) to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'turbo.json'
      - '.github/workflows/deploy-fe113.yml'

  workflow_dispatch:

env:
  APP_NAME: web

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          # cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm turbo build --filter=web

      - name: Check standalone
        run: |
          echo "===== standalone ====="
          ls -la apps/web/.next/standalone

          echo ""
          echo "===== standalone node_modules ====="
          find apps/web/.next/standalone/node_modules -maxdepth 3 -print || true

      - name: Prepare deployment package
        run: |
          mkdir deploy

          echo "===== Copy standalone ====="
          cp -LR apps/web/.next/standalone/. deploy/

          echo "===== Copy static ====="
          mkdir -p deploy/apps/web/.next
          cp -LR apps/web/.next/static deploy/apps/web/.next/

          echo "===== Copy public ====="
          if [ -d apps/web/public ]; then
            cp -LR apps/web/public deploy/apps/web/
            cp -LR apps/web/public deploy/
          fi

          echo "===== Create Azure server.js ====="
          cat <<EOF > deploy/server.js
          const path = require("path");
          process.chdir(path.join(__dirname, "apps/web"));
          require("./apps/web/server.js");
          EOF

          echo "===== Deploy Folder ====="
          find deploy -maxdepth 3 -print

      - name: Zip package
        run: |
          cd deploy
          zip -r ../release.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: test-app
          slot-name: Production
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F04AAB5CCACF4C2BA080D6B96649E287 }}
